### ISSUE TITLE
Unable to run cypress open

### ISSUE THREAD

**Issue by antarr** [shakacode/cypress-playwright-on-rails#123]
I'm getting this error 
```
Couldn't find a package.json file in "/Users/abyrd1/Code/store_project"
```
When calling `yarn cypress open --project ./spec`
I followed the instructions in the README for installing in `spec/cypress`

- cypress-on-rails (1.13.1)
- rails (5.2.8.1)

**Comment by grantspeelman** [comment]
where is the `package.json` file located and try changing into that directory and running `yarn cypress open`

EG

```shell
cd spec/cypress
yarn cypress open
```

**Comment by antarr** [comment]
The package.json is at spec/package.json. When I go into the directory that works. So need to update the Procfile, which I guess is fine.

### Procfile
```
server: CYPRESS=1 bundle exec rails s -p 5017
cypress: cd spec && yarn cypress open
```
